python ../train_model.py \
--data_root /home/whisper2024/PBVS/Unicorn_Dataset \
--output_dir ../runs/all_resnet101_eo_pretrained_mmd_17_64 \
--batch_size 128 \
--pretrained_path /home/mjh/challenge/pbvs2025/PBVS2025_mjh/EO_Pretrained/4.pth \
--epochs 20 \
--lr 1e-3 \
--optimizer adamw \
--use_feature_matching \
--feature_matching_weight 0.1 \
--gpus "0,1,2" \
--use_class_weights \
--contrastive_method none 